---
- name: Install nginx and publish simple page
  hosts: all
  gather_facts: true
  
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - curl
          - git
          - htop
        state: present
 
    - name: Install nginx (Debian/Ubuntu)
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install nginx (RHEL/CentOS)
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure web root exists
      ansible.builtin.file:
        path: "/var/www/html/"
        state: directory
        mode: '0755'

    - name: Write index.html
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        content: |
          <h1>테스트 입니다.</h1>
          <p>host={{ inventory_hostname }}</p>
          <p style='background-color:#222'>TETST</p>


    - name: Enable and start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
